version: '3'
services:
  mysqld:
    image: mysql:5.7
    container_name: mysqld
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=exporter
      - MYSQL_USER=exporter
      - MYSQL_PASSWORD=exporter
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - 3306:3306  

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/mime.types:/etc/nginx/mime.types:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
      
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    depends_on:
      - node_exporter

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'     

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    restart: unless-stopped
    command:
     - "--mysqld.username=exporter:exporter"
     - "--mysqld.address=mysqld:3306"
    ports:
      - 9104:9104
    links:
      - mysqld
    depends_on:
      - mysqld    

  plantuml-server:
    image: plantuml/plantuml-server:latest
    ports:
      - '9999:8080'

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - '8081:80'
      - '8080:443'
      - '2222:22'
    volumes:
      - './gitlab/config:/etc/gitlab:ro'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        pages_external_http=['http://plantuml-server:9999']  