version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wp_db
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
      - MYSQL_ROOT_PASSWORD=root_password

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf    
      - ./data/nginx/mime.types:/etc/nginx/mime.types

  grafana:
    image: grafana/grafana:10.0.1
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - '9090:9090'
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    depends_on:
      - node_exporter

  node_exporter:
    image: prom/node-exporter:v1.6.0
    ports:
      - '9100:9100'     

  plantuml-server:
    image: plantuml/plantuml-server:latest
    ports:
      - '9999:8080'

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        pages_external_http: ['http://plantuml-server:8080']  