{
 "title": "OS General",
 "tags": [ "linux" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Количество файловых дескрипторов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_filefd_allocated" }
   ]
  },
  {
   "title": "Полученный\\отправленный трафик",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Использование дискового пространства",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}